apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
      tier: frontend
  template:
    metadata:
      labels:
        app: proxy
        tier: frontend
    spec:
      containers:
        - name: proxy
          image: "proxy:0.1"
          ports:
            - containerPort: 8080

---
#service

apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  externalIPs: 
    - 80.11.12.10